---
- name: "Create init file for ucarp"
  template:
    src: "ucarp.service.j2"
    dest: "/etc/systemd/system/ucarp-{{ item.name }}.service"
    mode: '0644'
  register: init
  with_items:
    - "{{ ucarp_config }}"
  notify:
    - "restart ucarp"

- name: "Copy up scripts"
  template:
    src: "vip-up.sh.j2"
    dest: "/etc/ucarp/{{ item.name }}-up.sh"
    mode: '0755'
  register: upscript
  with_items:
    - "{{ ucarp_config }}"
  notify:
    - restart ucarp

- name: "Copy down scripts"
  template:
    src: "vip-down.sh.j2"
    dest: "/etc/ucarp/{{ item.name }}-down.sh"
    mode: '0755'
  register: downscript
  with_items:
    - "{{ ucarp_config }}"
  notify:
    - restart ucarp

- name: "Enable ucarp service"
  systemd:
    name: "ucarp-{{ item.name }}"
    enabled: true
    state: started
    daemon_reload: true
  with_items:
    - "{{ ucarp_config }}"

- name: "Remember which services need to restart"
  set_fact:
    restart_services: "{{ restart_services | default([]) + [item.item.name] |unique }}"
  when: item.changed
  with_items: 
    - "{{ init.results }}"
    - "{{ upscript.results }}"
    - "{{ downscript.results }}"

- debug:
    var: restart_services 
