---
- name: "Restart ucarp"
  ansible.builtin.service:
    name: "ucarp-{{ item.name }}"
    daemon_reload: true
    state: restarted
  when: item.name in restart_services | default([])
  with_items: "{{ ucarp_config }}"
